### ISSUE TITLE
sublime_test3 3176安装完扩展后，执行LUA:Rebulid Tag报错：Traceback (most recent call last):   File "D:\Program Files\sublime_text3\sublime_plugin.py", line 1072, in run_     return self.run(edit)   File "D:\Program Files\sublime_text3\Data\Packages\LuaJumpDefinition\execute.py", line 154, in run     all_the_text = file_object.readlines()   File "./python3.3/codecs.py", line 313, in decode UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 3490: invalid start byte reloading plugin LuaJumpDefinition.execute

### ISSUE THREAD

**Issue by DelayCat** [RuiZhuo/LuaJumpDefinition#3]
execute.py 文件第152行 ： file_object = open(filePath, 'rt', encoding="utf-8") 更改为 file_object = open(filePath, 'rt', encoding="utf-8", errors='ignore') 后报错消失。

**Comment by RuiZhuo** [comment]
过了这么久，居然有人用哈。 重新执行一遍LUA:Rebuild Tag就可以了。
